Script started on Mon Sep 30 06:57:46 2019
$ python test_diffk.y py
-----
MUTAG - DiffK
Val Loss: 0.3682, Test Accuracy: 0.850 + 0.051, Duration: 4.607
Val Loss: 0.3559, Test Accuracy: 0.849 + 0.069, Duration: 4.547
Val Loss: 0.3561, Test Accuracy: 0.833 + 0.082, Duration: 4.854
Val Loss: 0.3569, Test Accuracy: 0.843 + 0.086, Duration: 4.983
Val Loss: 0.3822, Test Accuracy: 0.835 + 0.070, Duration: 4.446
Val Loss: 0.3596, Test Accuracy: 0.849 + 0.087, Duration: 4.297
Val Loss: 0.3511, Test Accuracy: 0.838 + 0.089, Duration: 4.309
Val Loss: 0.3589, Test Accuracy: 0.854 + 0.076, Duration: 4.357
Val Loss: 0.3793, Test Accuracy: 0.844 + 0.082, Duration: 4.288
Val Loss: 0.3619, Test Accuracy: 0.849 + 0.087, Duration: 4.296
Val Loss: 0.3476, Test Accuracy: 0.854 + 0.088, Duration: 4.422
Val Loss: 0.3568, Test Accuracy: 0.854 + 0.088, Duration: 4.370
Traceback (most recent call last):
  File "test_diffk.py", line 76, in <module>
    logger=None)
  File "/home/user/pytorch_geometric/benchmark/kernel/train_eval.py", line 53, in cross_validation_with_val_set
    train_loss = train(model, optimizer, train_loader)
  File "/home/user/pytorch_geometric/benchmark/kernel/train_eval.py", line 125, in train
    out = model(data)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/pytorch_geometric/benchmark/kernel/diffk.py", line 72, in forward
    s = pool_block(x, adj)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/pytorch_geometric/benchmark/kernel/diffk.py", line 28, in forward
    x2 = F.relu(self.conv2(x1, adj, mask, add_loop))
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch_geometric/nn/dense/dense_sage_conv.py", line 60, in forward
    out = out / adj.sum(dim=-1, keepdim=True).clamp(min=1)
RuntimeError: CUDA error: device-side assert triggered
$ ^[[A^[[A^C
$ ^Z

Script done on Mon Sep 30 07:21:09 2019
